tabname: Tonkeeper Web Deploy
on:
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                description: Deploy to env
                required: true
               esc options:
                    - dev
                    - main

tabjobs:
    web-deploy:
        uses: ./.github/workflows/web-build.yaml
        with:
            environment: ${{ inputs.environment }}
        secrets: inherit

    web-tests:
        needs: web-deploy
        uses: ./.github/workflows/web-tests.yaml
        with:
            base-url: ${{ needs.web-deploy.outputs.deployment-url }}
        secrets: inherit
