name: Tonkeeper Swap Widget Deploy
on:
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                description: Deploy to env
                required: true
                options:
                    - dev
                    - main

jobs:
    swap-widget:
        uses: ./.github/workflows/swap-widget-build.yaml
        with:
            environment: ${{ inputs.environment }}
        secrets: inherit
